apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-2
  namespace: serverless-functions
spec:
  version: "v1.0.0"
  image: "registry-01.cloud.cmctelecom.vn/default-1351-bgwasrxyt9qj/vunt-cloudfunction-lab-func-2"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "hello_world"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
    srcRepo:
      url: "https://github.com/vuchtbk272000/openfunction-python-helloworld.git"
      sourceSubPath: "function-2"
      revision: "615c3f2d23ab9ba4707ca81851641db1e8a43677"
      credentials:
        name: git-repo-secret
  serving:
    runtime: "knative"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
