apiVersion: core.openfunction.io/v1beta1
kind: Function
metadata:
  name: function-3
  namespace: serverless-functions
spec:
  version: "v1.0.0"
  image: "vuxucam/openfunction-python-helloworld:v1"
  imageCredentials:
    name: push-secret
  build:
    builder: "openfunction/gcp-builder:v1"
    env:
      GOOGLE_FUNCTION_TARGET: "hello_world"
      GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
      GOOGLE_FUNCTION_SOURCE: "main.py"
    srcRepo:
      url: "https://github.com/vuchtbk272000/openfunction-python-helloworld.git"
      sourceSubPath: "function-2"
      revision: "885871706697ea4258474ac8e8aba846ec46da8e"
      credentials:
        name: git-repo-secret
  serving:
    runtime: "knative"
    template:
      containers:
        - name: function
          imagePullPolicy: IfNotPresent
