{{- if .Values.secrets.enabled }}
{{- $regUser := .Values.secrets.registry.username | default "" }}
{{- $regPass := .Values.secrets.registry.password | default "" }}
{{- $regAuth := .Values.secrets.registry.auth | default "" }}
{{- if and (eq $regAuth "") $regUser $regPass }}
{{- $regAuth = printf "%s:%s" $regUser $regPass | b64enc }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    build.shipwright.io/referenced.secret: "true"
  labels:
    {{- include "function-template.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{ .Values.secrets.registry.server | quote }}: {
          "username": {{ $regUser | quote }},
          "password": {{ $regPass | quote }},
          "email": {{ .Values.secrets.registry.email | default "" | quote }},
          "auth": {{ $regAuth | quote }}
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitCredentials.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    build.shipwright.io/referenced.secret: "true"
  labels:
    {{- include "function-template.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.git.username | default "" | quote }}
  password: {{ .Values.secrets.git.password | default "" | quote }}
{{- end }}
