{{- if .Values.secrets.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.imageCredentials.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    build.shipwright.io/referenced.secret: "true"
  labels:
    {{- include "function-template.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        {{ .Values.secrets.registry.server | quote }}: {
          "username": {{ .Values.secrets.registry.username | quote }},
          "password": {{ .Values.secrets.registry.password | quote }},
          "email": {{ .Values.secrets.registry.email | quote }},
          "auth": {{ .Values.secrets.registry.auth | quote }}
        }
      }
    }
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitCredentials.name }}
  namespace: {{ .Values.namespace.name }}
  annotations:
    build.shipwright.io/referenced.secret: "true"
  labels:
    {{- include "function-template.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.secrets.git.username | quote }}
  password: {{ .Values.secrets.git.password | quote }}
{{- end }}
