function-template:
  nameOverride: "tenant-b"
  fullnameOverride: "tenant-b"

  namespace:
    name: tenant-b-lambda

  functions:
    - name: function-1
      version: "v1.0.0"
      image: "vuxucam/openfunction-python-helloworld:v1"
      build:
        env:
          GOOGLE_FUNCTION_TARGET: "hello_world"
          GOOGLE_FUNCTION_SIGNATURE_TYPE: "http"
          GOOGLE_FUNCTION_SOURCE: "main.py"
        srcRepo:
          url: "https://github.com/vuchtbk272000/openfunction-python-helloworld.git"
          sourceSubPath: "function-1"
          revision: "abfb598c7c22f6ea0c0f003f3c0b230a8d137fd7"
